# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentpane < Formula
  desc "tmux-based environment for managing AI coding agent panes"
  homepage "https://github.com/minghinmatthewlam/agentpane"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/minghinmatthewlam/agentpane/releases/download/v0.1.5/agentpane_0.1.5_darwin_amd64.tar.gz"
      sha256 "40844858f555a737e1185e153a41f01989548bf1bf1ab99531c20a681bf2ab4a"

      def install
        bin.install "agentpane"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/minghinmatthewlam/agentpane/releases/download/v0.1.5/agentpane_0.1.5_darwin_arm64.tar.gz"
      sha256 "6cd6e1bcf61e253db8d0ea38cdfeadebff22ce0799f82ab968bca88014d302dd"

      def install
        bin.install "agentpane"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/minghinmatthewlam/agentpane/releases/download/v0.1.5/agentpane_0.1.5_linux_amd64.tar.gz"
      sha256 "bb7e2b4ce8d723d92d84a458f38a2722ac64d3c698a81f9d5f4bbeb062fed35e"
      def install
        bin.install "agentpane"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/minghinmatthewlam/agentpane/releases/download/v0.1.5/agentpane_0.1.5_linux_arm64.tar.gz"
      sha256 "a1c431225a6f17e331261b3bc480acfa0be912b64f28005056d7e9d5eb318cf1"
      def install
        bin.install "agentpane"
      end
    end
  end

  test do
    system "#{bin}/agentpane", "--help"
  end
end
