# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentpane < Formula
  desc "tmux-based environment for managing AI coding agent panes"
  homepage "https://github.com/minghinmatthewlam/agentpane"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/minghinmatthewlam/agentpane/releases/download/v0.1.6/agentpane_0.1.6_darwin_amd64.tar.gz"
      sha256 "b7f0b7f962e351ebca1704a749c1372f5a5f943fd1ea53dd9b620f08ad61533f"

      def install
        bin.install "agentpane"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/minghinmatthewlam/agentpane/releases/download/v0.1.6/agentpane_0.1.6_darwin_arm64.tar.gz"
      sha256 "e1e3c852bf396baee39bf5c252523e6dd1543c00982f30f98b9b7beb641a2f52"

      def install
        bin.install "agentpane"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/minghinmatthewlam/agentpane/releases/download/v0.1.6/agentpane_0.1.6_linux_amd64.tar.gz"
      sha256 "96391fa5c2e0679f02f0a12c298a9ea8b544ee2f83daec29bb43e3f44185d58c"
      def install
        bin.install "agentpane"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/minghinmatthewlam/agentpane/releases/download/v0.1.6/agentpane_0.1.6_linux_arm64.tar.gz"
      sha256 "25aa271834ff105cd6c5add3fc817813aeff55cdd20c00bc57fb031b3f298083"
      def install
        bin.install "agentpane"
      end
    end
  end

  test do
    system "#{bin}/agentpane", "--help"
  end
end
